services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: codegrader
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - codegrader-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10
  backend:
    build: ./backend
    ports:
      - "${SERVER_PORT:-8080}:8080"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      SERVER_PORT: ${SERVER_PORT:-8080}
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - codegrader-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - codegrader-network

volumes:
  postgres_data:

networks:
  codegrader-network:
    driver: bridge
